apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2  # Default number of replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx  # Name of the container
        image: nginx:1.21  # Using a specific version of the nginx image
        ports:
        - containerPort: 80  # Exposing port 80 for the container
