apiVersion: v1
kind: Service
metadata:
  name: nginx-service  # Service name
spec:
  selector:
    app: nginx  # Matches the label in the deployment
  ports:
  - protocol: TCP
    port: 80  # Exposed port for the service
    targetPort: 80  # Port inside the container
